#' Compute lambda
#'
#' Calculates the expected real rate of exogenous mortgage repayment
#' based on various financial parameters.  This function implements
#' the formula described on page 603 (p. 13 of pdf) from Agarwal et
#' al. (2013).
#'
#' @param mu Probability of moving each year (as a decimal); Agarwal
#'   et al. assume 0.1 or an expected duration of staying in the house
#'   of 10 years.
#' @param i_0 The nominal interest rate of the mortgage.
#' @param gamma_uppercase The remaining life of the mortgage in years.
#' @param pi The inflation rate.
#'
#' @return The expected real rate of exogenous mortgage repayment.
#'
#' @references
#' Agarwal et al., 2013, p. 603 (p. 13 of pdf)
#'
#' @examples
#' lambda_agarwal_et_al_p_603_example <- compute_lambda(
#'  mu = 0.1, i_0 = 0.06, gamma_uppercase = 25, pi = 0.03
#') |>
#'  round(3)
#' stopifnot(lambda_agarwal_et_al_p_603_example == 0.147)
#'
#' @export
compute_lambda <- function(mu, i_0, gamma_uppercase, pi) {
  lambda <- mu + i_0 / (exp(i_0 * gamma_uppercase) - 1) + pi
  return(lambda)
}


#' Compute psi
#'
#' Calculates the psi value based on the real discount rate, the
#' expected real rate of exogenous mortgage repayment, and the
#' annualized standard deviation of the mortgage interest rate. This
#' function implements the formula and parameters as described in
#' Agarwal et al. (2013).
#'
#' @param rho The real discount rate, which equals the nominal
#'   interest rate minus the inflation rate.
#'   See Agarwal et al. (2013) p. 606 (p. 16 of the pdf) and the Fisher equation for
#'   details.
#'   Fisher equation: https://en.wikipedia.org/wiki/Fisher_equation
#' 
#' @param lambda The expected real rate of exogenous mortgage
#'   repayment.
#' @param sigma The annualized standard deviation of the mortgage
#'   interest rate.  See footnote 15 in Agarwal et al. (2013) for
#'   details.
#'
#' @return psi value as described in the referenced source. [ChatGPT explanation of psi](https://chat.openai.com/share/90c95875-8940-4979-aaf2-bc0acff5282b)
#'
#' @references
#' Agarwal et al., 2013, p. 603 (p. 13 of pdf)
#' [Wikipedia Fisher Equation](https://en.wikipedia.org/wiki/Fisher_equation)
#' [ChatGPT Fisher Equation](https://chat.openai.com/share/4b0d0bb5-8572-4540-8841-24a5cacdffe6)
#'
#' @examples
#' compute_psi(rho = 0.05, lambda = 0.147, sigma = 0.0109)
#' @export
compute_psi <- function(rho, lambda, sigma) {
  psi <- sqrt(2 * (rho + lambda)) / sigma
  return(psi)
}

#' Compute kappa(M) for Itemized Mortgage Payments
#'
#' Calculates the real, tax-adjusted cost of refinancing a mortgage, considering various financial parameters
#' and costs involved in the process. Implements the formula described in Agarwal et al. (2013), specifically equation A3 in Appendix A.
#'
#' @param F The fixed cost of refinancing.
#' @param f `100 * f` is the number of points (so, specify the points as a decimal).
#' @param M The real value of remaining principal.
#' @param tau The marginal tax rate.
#' @param mu Probability of moving each year (as a decimal); Agarwal et al. assume 0.1
#'   or an expected duration of staying in the house of 10 years.
#' @param rho The real discount rate.
#' @param pi The inflation rate.
#' @param N The number of years for the new mortgage after refinancing.
#'
#' @return Kappa(M) -- the real, tax-adjusted cost of refinance. These
#'   costs include points and any other explicit or implicit
#'   transaction costs (such as lawyers fees, mortgage insurance,
#'   personal time). Kappa(M) is the net present value (NPV) of these
#'   costs, netting out all allowable tax deductions generated by
#'   future deductions of amortized refinancing points.
#'
#' @references
#' Agarwal et al. (2013), p. 595 (p. 5 of pdf), Equation A3
#'
#' @examples
#' compute_kappa_M_itemize_mtg_pymts(2000, 0.01, 100000, 0.25, 0.1, 0.03, 0.02, 30)
#'
#' @export
compute_kappa_M_itemize_mtg_pymts <- function(F, f, M, tau, mu, rho, pi, N) {
  theta <- mu + 0.10

  frac1 <- tau / (theta + rho + pi)
  frac2 <- (1 - exp(-(theta + rho + pi) * N)) / N
  frac3 <- (rho + pi) / (theta + rho + pi)

  kappa_M <- F + f * M * (1 - frac1 * (frac2 * frac3 + theta))

  return(kappa_M)
}



#' Compute kappa(M) Without Itemizing Mortgage Payments
#'
#' Calculates the real, tax-adjusted cost of refinancing a mortgage
#' without itemizing deductions, considering points, the remaining
#' principal, and fixed transaction costs. Implements the calculation
#' as per Agarwal et al. (2013), referenced in equation A3 in Appendix
#' A.
#'
#' @param f Points where `100 * f` is the number of points (so `f` is
#'   the points in decimal form)
#' @param M The real value of the remaining principal.
#' @param F The fixed transaction costs of refinancing (e.g.,lawyers fees, mortgage
#'   insurance, personal time).
#'
#' @return Kappa(M) -- the real, tax-adjusted cost of refinance. These
#'   costs include points and any other explicit or implicit
#'   transaction costs. Kappa(M) is the net present value (NPV) of
#'   these costs, netting out all allowable tax deductions generated
#'   by future deductions of amortized refinancing points.
#'
#' @references
#' Agarwal et al. (2013), Equation A3, p. 595 (p. 5 of pdf). 
#'
#' @examples
#' compute_kappa_M_no_itemizing_of_mtg_pymts(0.01, 100000, 2000)
#'
#' @export
compute_kappa_M_no_itemizing_of_mtg_pymts <- function(f, M, F) {
  kappa_M <- f * M + F
  return(kappa_M)
}


#' Compute C(M) - Cost of Refinancing Normalized for Tax Rate
#'
#' Calculates the cost of refinancing normalized for the tax rate,
#' based on the real, tax-adjusted cost of refinance.  
#'
#' @param kappa The real, tax-adjusted cost of refinance which
#'   includes points and any other explicit or implicit transaction
#'   costs.  Kappa(M) is the net present value (NPV) of these costs,
#'   netting out all allowable tax deductions generated by future
#'   deductions of amortized refinancing points.
#' @param tau The marginal tax rate.
#'
#' @return C(M): The cost of refinancing normalized for the tax rate, tau.
#'
#' @references
#' Agarwal et al. (2013), p. 595 (p. 5 of pdf).
#'
#' @examples
#' # compute_C_M(2000, 0.25)
#'
#' @export
compute_C_M <- function(kappa, tau) {
  C_M <- kappa / (1 - tau)
  return(C_M)
}


#' Compute phi
#'
#' Calculates the phi value based on the psi value from the
#' compute_psi function, the real discount rate, the expected real
#' rate of exogenous mortgage repayment, the real, tax-adjusted cost
#' of refinance, the remaining principal, and the marginal tax
#' rate. 
#'
#' @param psi Input from the compute_psi function.
#' @param rho The real discount rate, which equals the nominal
#'   interest rate minus the inflation rate.  See Agarwal et
#'   al. (2013) p. 606 (p. 16 of the pdf) and the Fisher equation for
#'   details.
#' @param lambda The expected real rate of exogenous mortgage
#'   repayment.
#' @param kappa The real, tax-adjusted cost of refinance which
#'   includes points and any other explicit or implicit transaction
#'   costs.  Kappa(M) is the net present value (NPV) of these costs,
#'   netting out all allowable tax deductions generated by future
#'   deductions of amortized refinancing points.
#' @param M The real value of the remaining principal.
#' @param tau The marginal tax rate.
#'
#' @return Phi value as described in the referenced source.
#'
#' @references
#' Agarwal et al. (2013)
#' Fisher Equation: https://en.wikipedia.org/wiki/Fisher_equation
#'
#' @examples
#' psi_value <- compute_psi(rho = 0.05, lambda = 0.147, sigma = 0.0109)
#' compute_phi(psi = psi_value, rho = 0.05, lambda = 0.147, kappa = 5000,
#'             M = 100000, tau = 0.28)
#'
#' @export
compute_phi <- function(psi, rho, lambda, kappa, M, tau) {
  phi <- 1 + psi * (rho + lambda) * (kappa / M) / (1 - tau)
  return(phi)
}

#' Compute x* (Short Version)
#'
#' Calculates the threshold for the refinance decision so that the
#' borrower should refinance when the current mortgage interest rate
#' minus the original mortgage interest rate is less than or equal to
#' x*. This function uses the psi and phi values, likely obtained from
#' the compute_psi() and compute_phi() functions, respectively.
#'
#' @param psi Psi value, likely from the compute_psi() function.
#' @param phi Phi value, likely from the compute_phi() function.
#'
#' @return x_star: The threshold for the refinance decision.
#'
#' @details The borrower should refinance when i - i_0 <= x_star,
#'   where i represents the current mortgage interest rate and i_0
#'   represents the original mortgage interest rate. The calculation
#'   involves the main branch of the Lambert W function, specifically
#'   gsl::lambert_W0 in the GNU Scientific Library.
#'
#' @examples
#' psi_value <- compute_psi(rho = 0.05, lambda = 0.147, sigma = 0.0109)
#' phi_value <- compute_phi(psi_value, rho = 0.05, lambda = 0.147,
#'                          kappa = 9904.783, M = 1e06, tau = 0.28)
#' compute_x_star_short(psi_value, phi_value)
#'
#' @export
compute_x_star_short <- function(psi, phi) {
  x_star <- (1 / psi) * (phi + gsl::lambert_W0(-1 * exp(-1 * phi)))
  return(x_star)
}



#' Compute x* 
#'
#' Calculates the threshold for the refinance decision so that the
#' borrower should refinance when the current mortgage interest rate
#' minus the original mortgage interest rate is less than or equal to
#' x*.
#'
#' @param rho The real discount rate, which equals the nominal
#'   interest rate minus the inflation rate.
#' @param sigma The annualized standard deviation of the mortgage
#'   interest rate.
#' @param mu Probability of moving each year (as a decimal).
#' @param i_0 The nominal interest rate of the mortgage.
#' @param gamma_uppercase The remaining life of the mortgage in years.
#' @param pi The inflation rate.
#' @param tau The marginal tax rate.
#' @param M The real value of the remaining principal.
#' @param kappa The real, tax-adjusted cost of refinance (see p. 595
#'   p. 5 of the pdf of Agarwal et al. 2013). These costs include
#'   points and any other explicit or implicit transaction costs (such
#'   as lawyers fees, mortgage insurance, personal time). kappa(M)
#'   is the net present value (NPV) of these costs, netting out all
#'   allowable tax deductions generated by future deductions of
#'   amortized refinancing point.
#'
#' @return x_star: The threshold for the refinance decision,
#'   indicating that the borrower should refinance when the current
#'   mortgage interest rate minus the original mortgage interest rate
#'   is less than or equal to x_star.
#'
#' @details The borrower should refinance when i - i_0 <= x_star,
#'   where i represents the current mortgage interest rate and i_0
#'   represents the original mortgage interest rate.
#'
#' @examples
#' compute_x_star(rho = 0.03, sigma = 0.1, mu = 0.1, i_0 = 0.05,
#'                gamma_uppercase = 30, pi = 0.02, tau = 0.25, M = 100000,
#'                kappa = 9904.783)
#'
#' @export
compute_x_star <- function(rho, sigma, mu, i_0, gamma_uppercase, pi, tau, M, kappa) {
  
  lambda <- compute_lambda(mu = mu, i_0 = i_0, gamma_uppercase = gamma_uppercase,
                           pi = pi)
  psi <- compute_psi(rho = rho, lambda = lambda, sigma = sigma)
  phi <- compute_phi(psi = psi, rho = rho, lambda = lambda, kappa = kappa,
                     M = M, tau = tau)
  
  x_star <- compute_x_star_short(psi = psi, phi = phi)

  return(x_star)
}

#' Compute x* Using Second Order Square Root Rule
#'
#' Calculates the threshold for the refinance decision based on the
#' second-order square root rule. This method is based on the
#' calculation detailed in Agarwal et al. (2013), particularly on page
#' 601 (p. 11 of the PDF).
#'
#' @param sigma The annualized standard deviation of the mortgage
#'   interest rate. In footnote 15, Argarwal et al. (2013) use the
#'   annualized standard deviation of the monthly Freddie Mac 30-year
#'   mortgage rate.
#' @param kappa The real, tax-adjusted cost of refinance(see p. 595
#'   p. 5 of the pdf of Agarwal et al. 2013). These costs include
#'   points and any other explicit or implicit transaction costs (such
#'   as lawyers fees, mortgage insurance, personal time). kappa(M)
#'   is the net present value (NPV) of these costs, netting out all
#'   allowable tax deductions generated by future deductions of
#'   amortized refinancing point.
#' @param M The real value of the remaining principal.
#' @param tau The marginal tax rate.
#' @param rho The real discount rate.
#' @param mu Probability of moving each year (as a decimal).
#' @param i_0 The nominal interest rate of the mortgage.
#' @param gamma_uppercase The remaining life of the mortgage in years.
#' @param pi The inflation rate.
#'
#' @return x_star: The threshold for the refinance decision based on
#'   the second-order square root rule.
#'
#' @details The function computes lambda and then calculates x* using
#'   the formula at the bottom of p. 601 (p. 11 of the PDF) from
#'   Agarwal et al. (2013). The calculation involves a square root
#'   term and is based on the second-order approximation.
#'
#' @examples
#' compute_x_star_2nd_order_sqrt_rule(
#'   sigma = 0.1, kappa = 2000, M = 100000, tau = 0.25, rho = 0.03, mu = 0.1,
#'   i_0 = 0.05, gamma_uppercase = 30, pi = 0.02
#' )
#'
#' @export
compute_x_star_2nd_order_sqrt_rule <- function(sigma, kappa, M, tau, rho, mu, i_0,
                                               gamma_uppercase, pi) {
  
  lambda <- compute_lambda(mu = mu, i_0 = i_0, gamma_uppercase = gamma_uppercase,
                           pi = pi)

  # For the square-root rule equation at the bottom of p. 601 (p. 11 of the pdf),
  # create frac1 and sqrt1 for readability
  frac1 <- (sigma * kappa) / (M * (1 - tau))
  sqrt1 <- sqrt(2 * (rho + lambda))

  # Note that we'll leave off the negative sign for the equation at the bottom of
  # p. 601 (p. 11 of the pdf), so the result will not be negative and match the
  # calibrations in Table 1.
  x_star <- sqrt(frac1 * sqrt1)
  
  return(x_star)
}


#' Compute Present Value Breakeven Threshold
#'
#' Calculates the present value breakeven threshold for refinancing a
#' mortgage. This threshold is based on the cost of refinancing
#' normalized for the tax rate, the real discount rate, the expected
#' real rate of exogenous mortgage repayment, and the remaining
#' principal. Implements the calculation as per equation 22 in Agarwal
#' et al. (2013).
#'
#' @param C_M Cost of refinancing normalized for the tax rate, tau.
#' @param rho The real discount rate. Using the Fisher equation, the
#'   real discount rate equals nominal interest rate minus the
#'   inflation rate.
#' @param lambda The expected real rate of exogenous mortgage
#'   repayment.
#' @param M The real value of the remaining principal.
#'
#' @return x_pv: The present value breakeven threshold for refinancing a mortgage.
#'
#' @examples
#' compute_pv_breakeven_threshold(C_M = 2000, rho = 0.05, lambda = 0.05, M = 100000)
#'
#' @export
compute_pv_breakeven_threshold <- function(C_M, rho, lambda, M) {
  x_pv <- C_M * (rho + lambda) / M
  return(x_pv)
}
